### ISSUE TITLE
Various problems when running npm install in snipcard-theme folder

### ISSUE THREAD

**Issue by winterflags** [snipcart/snipcart-theme#10]
Hi, I'm a total newbie when it comes to NodeJS and the other tools needed to customize Snipcart. However, I do really need to be able to customize it for use on my website, as the appearances matter a lot.

I've downloaded and unpacked `snipcart-theme` on my Mac, and installed `node` and `npm` with homebrew.

When running `npm install` in the `snipcard-theme` folder, it starts a lengthy process where towards the end I get these errors. I have no idea what they mean. I would need to know if they're related to the `snipcard-theme` files/dependencies being outdated, or if there's problems with my `node`/`npm` installs. Thanks!

```
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:174:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:167:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:160:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cpp:1:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:174:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/myuser/.node-gyp/10.10.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myuser/MySnipCartProject/snipcart-theme-master/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.10.0/bin/node" "/Users/myuser/MySnipCartProject/snipcart-theme-master/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/myuser/MySnipCartProject/snipcart-theme-master/node_modules/node-sass
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2018-09-12T17_04_55_358Z-debug.log
```

**Comment by thatfrankdev** [comment]
Thanks for reporting this.

While running the install using Node LTS version, we should support Node's latest stable version as well.
