### ISSUE TITLE
Gulp Error — assert.js:350

### ISSUE THREAD

**Issue by isaactopo** [snipcart/snipcart-theme#18]
HI, 
when I run the ```gulp```command the terminal is throwing this error: 

```
snipcart-theme git:(master) ✗ gulp
[14:45:01] Requiring external module coffeescript/register
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Volumes/HD/Sites/snipcart-theme/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Volumes/HD/Sites/snipcart-theme/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Volumes/HD/Sites/snipcart-theme/gulpfile.coffee:38:6)
    at Object.<anonymous> (/Volumes/HD/Sites/snipcart-theme/gulpfile.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.loadFile (/Volumes/HD/Sites/snipcart-theme/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/Volumes/HD/Sites/snipcart-theme/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/local/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:195:5)
    at /usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:165:9
    at /usr/local/lib/node_modules/gulp-cli/node_modules/v8flags/index.js:135:14
    at /usr/local/lib/node_modules/gulp-cli/node_modules/v8flags/index.js:41:14
    at /usr/local/lib/node_modules/gulp-cli/node_modules/v8flags/index.js:53:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Any idea how to solve this?
Thanks in advance.

**Comment by JeanSebTr** [comment]
Hi @isaactopo :)

What OS and version of Nodejs are you using?

**Comment by isaactopo** [comment]
Hi @JeanSebTr 
I'm using OSX 10.11.5 and Node v10.15.3

**Comment by JeanSebTr** [comment]
Just tested with node 10.x and it works

Maybe try running it through `npx` to use the gulp version of the project. `npx gulp`
or running `npm start`

**Comment by isaactopo** [comment]
Hi @JeanSebTr 
`npx gulp` does the same, `npm start` is throwing this:

```
➜  snipcart-theme git:(master) ✗ npm start

> snipcart-themes@2.0.0 start /Volumes/HD/Sites/snipcart-theme
> gulp sync

[10:18:06] Requiring external module coffeescript/register
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Volumes/HD/Sites/snipcart-theme/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Volumes/HD/Sites/snipcart-theme/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Volumes/HD/Sites/snipcart-theme/gulpfile.coffee:38:6)
    at Object.<anonymous> (/Volumes/HD/Sites/snipcart-theme/gulpfile.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.loadFile (/Volumes/HD/Sites/snipcart-theme/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/Volumes/HD/Sites/snipcart-theme/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/Volumes/HD/Sites/snipcart-theme/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/Volumes/HD/Sites/snipcart-theme/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)
    at Liftoff.execute (/Volumes/HD/Sites/snipcart-theme/node_modules/liftoff/index.js:201:12)
    at module.exports (/Volumes/HD/Sites/snipcart-theme/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Volumes/HD/Sites/snipcart-theme/node_modules/liftoff/index.js:191:5)
    at /Volumes/HD/Sites/snipcart-theme/node_modules/liftoff/index.js:149:9
    at /Volumes/HD/Sites/snipcart-theme/node_modules/v8flags/index.js:138:14
    at /Volumes/HD/Sites/snipcart-theme/node_modules/v8flags/index.js:41:14
    at /Volumes/HD/Sites/snipcart-theme/node_modules/v8flags/index.js:53:7
    at process._tickCallback (internal/process/next_tick.js:61:11)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snipcart-themes@2.0.0 start: `gulp sync`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snipcart-themes@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2019-10-16T08_18_07_502Z-debug.log
```
It could be because of Gulp version?
